In [1]:
!pip -q install plotly

import pandas as pd
import numpy as np
import plotly.express as px

In [7]:
df = pd.read_csv("countries-aggregated.csv")
print(df.shape)
print(df.head())
df["Active"]= df["Confirmed"] - df["Recovered"] - df["Deaths"]

(161568, 5)
         Date      Country  Confirmed  Recovered  Deaths
0  2020-01-22  Afghanistan          0          0       0
1  2020-01-23  Afghanistan          0          0       0
2  2020-01-24  Afghanistan          0          0       0
3  2020-01-25  Afghanistan          0          0       0
4  2020-01-26  Afghanistan          0          0       0

In [8]:
df["Date"]= pd.to_datetime(df["Date"])
df["Active"]= df["Confirmed"]-df["Recovered"]-df["Deaths"]
df["Active"]=df["Active"].clip(lower=0)
df.head()

        Date      Country  Confirmed  Recovered  Deaths  Active
0 2020-01-22  Afghanistan          0          0       0       0
1 2020-01-23  Afghanistan          0          0       0       0
2 2020-01-24  Afghanistan          0          0       0       0
3 2020-01-25  Afghanistan          0          0       0       0
4 2020-01-26  Afghanistan          0          0       0       0

In [9]:
latest_date = df["Date"].max()
df_latest = df[df["Date"]==latest_date].copy()
df_latest.head()

           Date      Country  Confirmed  Recovered  Deaths  Active
815  2022-04-16  Afghanistan     178387          0    7676  170711
1631 2022-04-16      Albania     274462          0    3496  270966
2447 2022-04-16      Algeria     265739          0    6874  258865
3263 2022-04-16      Andorra      40709          0     153   40556
4079 2022-04-16       Angola      99194          0    1900   97294

In [16]:
fig_map=px.choropleth(
    df_latest,
    locations = "Country",
    locationmode = "country names",
    color = "Active",
    hover_name="Country",
    color_continuous_scale = "Reds",
    title= f"COVID-19 Active Cases - {latest_date.date()}"
)
fig_map.show()

In [19]:
top15 = df_latest.sort_values("Active",ascending=False).head(15)
fig_bar= px.bar(
    top15,
    x="Country",
    y = "Active",
    title="Top 15 Countries by Active COVID-19 Cases",
    text ="Active"
)
fig_bar.update_traces(texttemplate="%{text:,}",textposition="outside")
fig_bar.update_layout(xaxis_tickangle=-35)
fig_bar.show()

In [25]:
world = df.groupby("Date")[["Confirmed","Recovered","Deaths","Active"]].sum().reset_index()
fig_line = px.line(
    world,
    x="Date",
    y="Active",
    title="Global Active COVID-19 cases over time"
)
fig_line.show()

In [23]:
top15 = df_latest.sort_values("Active",ascending=False).head(15)
fig_bar= px.bar(
    top15,
    x="Country",
    y = "Active",
    title="Top 15 Countries by Active COVID-19 Cases",
    
)
fig_bar.update_traces(texttemplate="%{text:,}",textposition="outside")
fig_bar.update_layout(xaxis_tickangle=78)
fig_bar.show()